// Getters
export const CONTRACT_DATA_REQUEST = 'CONTRACT_DATA_REQUEST';
export const CONTRACT_DATA_SUCCESS = 'CONTRACT_DATA_SUCCESS';
export const CONTRACT_DATA_ERROR = 'CONTRACT_DATA_ERROR';

export const STATISTICS_SUCCESS = 'STATISTICS_SUCCESS';

export const ACTIVE_TRIGGERS_FETCHED = 'ACTIVE_TRIGGERS_FETCHED';


// Setters

export const TRIGGER_ADD_SUCCESS = 'TRIGGER_SUCCESS';

export const ADD_CONTRACT_REQUEST = 'ADD_CONTRACT_REQUEST';
export const ADD_CONTRACT_SUCCESS = 'ADD_CONTRACT_SUCCESS';
export const ADD_CONTRACT_ERROR = 'ADD_CONTRACT_ERROR';

export const NEW_ALERTS = 'NEW_ALERTS';
export const PAST_ALERTS = 'PAST_ALERTS';
