// Getters
export const CONTRACT_ID_REQUEST = 'CONTRACT_ID_REQUEST';
export const CONTRACT_ID_SUCCESS = 'CONTRACT_ID_SUCCESS';
export const CONTRACT_ID_ERROR = 'CONTRACT_ID_ERROR';

export const STATISTICS_SUCCESS = 'STATISTICS_SUCCESS';

export const ACTIVE_TRIGGERS_FETCHED = 'ACTIVE_TRIGGERS_FETCHED';


// Setters

export const TRIGGER_ADD_SUCCESS = 'TRIGGER_SUCCESS';
